# action.yml
name: Latex auto release
description: Automatically create relese with build latex files

inputs:
  files:
    description: Provide paths to latext files
    required: true

  repo-token:
    description: "GitHub secret token"
    required: true

outputs:
  is-success:
    description: Was build succesfully

runs:
  using: node12
  main: action/index.js
